config/routes.rb
Slim::Application.routes.draw do
  resources :workouts do
    member do
      get 'clone'
    end
  end

  devise_for :people
  resources :people do
    resources :workouts
    member do
      get 'dashboard'
      get 'overview'
    end
  end
  resources :bps

  devise_scope :person do
    get "/logout" => "devise/sessions#destroy"
  end

  resources :posts

  match 'measures/deleteall' => 'measures#deleteall'
  match 'measures/refresh' => 'measures#refresh'
  match 'measures/import' => 'measures#import'
  match 'measures/update_trend' => 'measures#update_trend'

  resources :measures
  match 'person/edit' => 'people#edit', :as => :edit_current_person

  match 'chart' => 'measures#chart'

  root :to => "people#index"

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  attr_accessible :description, :rating, :workout_date
  belongs_to :person
  validates_presence_of :person_id, :workout_date

  def self.user_grades(person_id)
    workouts = Workout.where(:person_id => person_id).order('workout_date desc')
    return grades(workouts)
  end

  def self.grade_range(workout_range)
  end

  def self.grades(workouts)
    return workouts
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  # GET /workouts
  # GET /workouts.json
  def index
    @person = Person.find params[:person_id]

    all_workout_days = @person.all_workout_days(@person.first_workout_date)
    @workouts = Kaminari.paginate_array(all_workout_days[:workouts]).page(params[:page]).per(40)
    @scores = all_workout_days[:scores]
    @against_goal = all_workout_days[:against_goal]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workouts }
    end
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
    @workout = Workout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workout }
    end
  end

def clone
  recent_workout = Workout.find(params[:id])
  new_workout = Workout.new
  new_workout.person_id = current_person.id
  new_workout.rating = recent_workout.rating
  new_workout.description = recent_workout.description
  new_workout.workout_date = Time.now
  new_workout.save
  redirect_to overview_person_path(current_person), notice: 'Workout was successfully cloned.'
end

  def new
    @workout = Workout.new
    @recent_workouts = Workout.where(:person_id => current_person.id).order('workout_date desc').limit(10)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workout }
    end
  end

  # GET /workouts/1/edit
  def edit
    @workout = Workout.find(params[:id])
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(params[:workout])
    @workout.person_id = current_person.id

    respond_to do |format|
      if @workout.save
        format.html { redirect_to overview_person_path(@workout.person), notice: 'Workout was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /workouts/1
  # PUT /workouts/1.json
  def update
    @workout = Workout.find(params[:id])

    respond_to do |format|
      if @workout.update_attributes(params[:workout])
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy

    respond_to do |format|
      format.html { redirect_to workouts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<div class='row'>
  <div class='span6'>
    <%= simple_form_for @workout do |f| %>
      <%= f.input :rating %>
      <%= f.input :description %>
      <%= f.input :workout_date %>
      <%= f.button :submit %>
    <% end %>
  </div>
  <div class='span6'>
    <h3>Clone a recent workout</h3>
    <ul>
      <% @recent_workouts.each do |workout| %>
        <li style='padding-bottom:20px;'>
        <%= link_to 'Clone', clone_workout_path(workout.id), :class=>'btn btn-primary' %>
        <%= workout.rating.to_s + ' ' + workout.description %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<h1>
  <%= image_tag @person.gravatar_url if Person.online %> <%= @person.name! %> 
  <small>
    <% workout_goal = @person.workout_goal || 300 %>
    7 day workout goal:<strong> <%= workout_goal.to_s %></strong>
  </small>
</h1>

<ul class="nav nav-pills">
  <li>
  <%= link_to 'Overview', overview_person_path(@person) %>
  </li>
  <li class="active">
  <%= link_to 'Workouts', '#' %>
  </li>
  <li>
  <%= link_to 'Weight', @person %>
  </li>
</ul>

<% if person_signed_in? %>
  <span class='pull-right'>
    <p>
    <%= link_to 'New Workout', new_workout_path, :class => 'btn btn-primary' %>
    </p>
  </span>
<% end %>

<table class='table'>
  <tr>
    <th>When</th>
    <th>Rating</th>
    <th>Description</th>
    <th>7 Day Score</th>
    <th>Grade</th>
    <th></th>
  </tr>

  <% @workouts.each do |workout| %>
    <tr>
      <td>
        <% if workout.workout_date %>
          <%= workout.workout_date.to_s(:slim) %>
          (<%= time_ago_in_words workout.workout_date %> ago)
        <% else %>
          -
        <% end %>
      </td>
      <td><%= workout.rating.nil? ? '-' : workout.rating %></td>
      <td><%= workout.description.nil? ? '-' : workout.description %></td>
      <td>
        <%= @against_goal[workout.workout_date.to_date].to_s %> /
        <%= @scores[workout.workout_date.to_date].to_s %>
      </td>
      <td><strong><%= Person.grade(@scores[workout.workout_date.to_date]) %></strong></td>
      <% if person_signed_in? and current_person.id == workout.person.id %>
        <td>
          <% if workout.id %>
            <%= link_to 'Edit', edit_workout_path(workout) %> |
            <%= link_to 'Delete', workout, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
<%= paginate @workouts %>
<br />

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render 'form' %>

app/views/workouts/show.html.erb
<p>
  <b>Rating:</b>
  <%= @workout.rating.nil? ? '-' : @workout.rating %>
</p>

<p>
  <b>Description:</b>
  <%= @workout.description.nil? ? '-' : @workout.description %>
</p>

<p>
  <b>When:</b>
  <%= @workout.workout_date.to_s(:slim) %>
</p>

<%= link_to 'Back', person_workouts_path(:person_id => @workout.person.id) %>