config/routes.rb
Slim::Application.routes.draw do
  resources :workouts do
    member do
      get 'clone'
    end
  end

  devise_for :people
  resources :people do
    resources :workouts
    member do
      get 'dashboard'
      get 'overview'
    end
  end
  resources :bps

  devise_scope :person do
    get "/logout" => "devise/sessions#destroy"
  end

  resources :posts

  match 'measures/deleteall' => 'measures#deleteall'
  match 'measures/refresh' => 'measures#refresh'
  match 'measures/import' => 'measures#import'
  match 'measures/update_trend' => 'measures#update_trend'

  resources :measures
  match 'person/edit' => 'people#edit', :as => :edit_current_person

  match 'chart' => 'measures#chart'

  root :to => "people#index"

end

app/models/person.rb
require 'withings'
include Withings

class Person < ActiveRecord::Base
  include Gravtastic

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  is_gravtastic

  attr_accessible :remember_me,:username, :email, :password, 
    :password_confirmation, :withings_id, :withings_api_key, 
    :height_feet, :height_inches, :goal,:goal_type,
    :private, :alpha, :binge_percentage, :measures_to_show, :time_to_send_email,
    :send_email, :workout_goal

  has_many      :measures
  has_many      :posts
  has_many      :workouts

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true
  validates_numericality_of :goal, :greater_than => 0, :less_than => 450, :on => :update
  validates_numericality_of :height_feet, :greater_than => 3, :less_than => 8
  validates_numericality_of :height_inches, :greater_than_or_equal_to => 0, :less_than => 12
  validates_numericality_of :alpha, :greater_than_or_equal_to => 0.1, :less_than => 0.3
  validates_numericality_of :binge_percentage, :greater_than_or_equal_to => 90, :less_than => 110
  validates_numericality_of :measures_to_show, :only_integer => true, :on => :update

  def first_workout_date
    if self.workouts.size > 0
      Workout.where(:person_id => self.id).order('workout_date asc').first.workout_date.to_date
    end
  end

  def first_record_date
    frd = Time.now.to_date
    first_measure = Measure.where(:person_id => self.id).order('measure_date asc').first

    if first_workout_date and first_workout_date < frd
      frd = first_workout_date
    end

    if first_measure and first_measure.measure_date < frd
      frd = first_measure.measure_date.to_date
    end
    frd
  end

  def get_current_measure(record_day)
    measures = self.measures.select{|m| m.measure_date.to_date == record_day}
    if measures.size == 0
      current_measure = Measure.new :measure_date => record_day,
        :person_id => self.id
    else
      #TODO: No double sessions!
      current_measure = measures.first
    end
    current_measure
  end

  def get_current_workout(workout_day)
    workouts = self.workouts.select{|w| w.workout_date.to_date == workout_day}
    if workouts.size == 0
      current_workout = Workout.new
      current_workout.workout_date = workout_day
      current_workout.person_id = self.id
      current_workout.rating = 0
    else
      #TODO: No double sessions!
      current_workout = workouts.first
    end
    current_workout
  end

  #Make sure they are padded for days with no workouts
  def grade_workout_range(workouts)
    workout_range = get_workout_range(workouts)
    workout_goal = self.workout_goal || 300
    current_score = workout_range.map { |workout| workout.rating }.sum
    workout_grade = ((current_score.to_f / workout_goal.to_f) * 100).to_i
    workout_grade = 100 if workout_grade > 100

    {
      :current_score => current_score,
      :workout_grade => workout_grade
    }
  end

  def get_workout_range(workouts)
    if workouts.size > 7
      workout_range = workouts[workouts.size - 7,
        workouts.size]
    else
      workout_range = Array.new
    end
    workout_range
  end

  def all_workout_days(workout_day = self.first_record_date)
    workout_days = Array.new
    score = Hash.new
    against_goal = Hash.new
    streak = Hash.new
    streak_counter = 0

    while workout_day <= Time.now.to_date do
      current_workout = get_current_workout(workout_day)
      workout_days << current_workout
      current_workout.rating == 0 if current_workout.rating.nil? or current_workout.nil?
      if current_workout.rating > 0
        streak_counter = streak_counter + 1
      else
        streak_counter = 0
      end

      gwr = grade_workout_range(workout_days)
      streak[workout_day] = streak_counter
      against_goal[workout_day] = gwr[:current_score]
      score[workout_day] = gwr[:workout_grade]
      workout_day = workout_day + 1.day
    end

    {
      :workouts => workout_days.reverse!.flatten,
      :scores => score,
      :streak => streak,
      :against_goal => against_goal
    }
  end

  def get_measures_hash
    mh = Hash.new

    self.measures.each do |m|
      mh[m.measure_date.to_date] = m
    end
    mh
  end

  def all_measure_days(loop_measure_day = self.first_record_date)
    #loop_measure_day = self.first_record_date
    weight_days = Hash.new
    karma_days = Hash.new
    trend_days = Hash.new
    measures_hash = get_measures_hash
    last_real_measure = nil

    #Problem is there may not be data for the random
    #day in the range where you start

    while loop_measure_day <= Time.now.to_date do
      current_measure = measures_hash[loop_measure_day.to_date]
      if current_measure.nil?
        unless last_real_measure.nil?
          current_measure = Measure.new :measure_date => loop_measure_day,
            :person_id => self.id, :karma => last_real_measure.karma
          weight_days[loop_measure_day] = last_real_measure.weight
          karma_days[loop_measure_day] = last_real_measure.karma
          trend_days[loop_measure_day] = last_real_measure.trend
        end
      else
        last_real_measure = current_measure
      end

      if current_measure and current_measure.weight
        weight_days[loop_measure_day] = current_measure.weight
        karma_days[loop_measure_day] = current_measure.karma
        trend_days[loop_measure_day] = current_measure.trend
      end
      loop_measure_day = loop_measure_day + 1.day
    end

    {
      :measures_hash => measures_hash,
      :weight => weight_days,
      :karma => karma_days,
      :trend_days => trend_days
    }
  end

  def self.online
    return true
  end

  def workout_percentage_this_year
    days_this_year = (Time.now.to_date - Date.parse('1/1/' + Time.now.year.to_s)).to_i
    year = Time.now.year
    Workout.where(:person_id => 1).select{|w| w.workout_date.year == year}.count
    return days_this_year
  end

  def name
    self.username
  end

  def name!
    return self.username.titleize
  end

  def has_trend
    self.measures.size > 6
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  def current_karma_grade
    karma_grade self.current_measure
  end

  def self.grade(grade_number)
    case grade_number
    when 100..1000
      karma_grade = 'A+'
      remainder = 5
    when 90..100
      karma_grade = 'A'
      remainder = grade_number - 90
    when 80..90
      karma_grade = 'B'
      remainder = grade_number - 80
    when 70..80
      karma_grade = 'C'
      remainder = grade_number - 70
    when 60..70
      karma_grade = 'D'
      remainder = grade_number - 60
    else
      karma_grade = 'F'
      remainder = 5
    end

    case remainder
    when 7..10
      karma_grade += '+'
    when 0..4
      karma_grade += '-'
    end 
    karma_grade
  end

  def karma_grade(measure)
    if measure == nil
      return "NA"
    end

    return Person.grade(measure.karma)
  end

  def get_bmi(weight)
    height = height_feet * 12 + height_inches
    return (weight * 703 / height**2)
  end

  #This method returns the trend over some number of days
  def trend_range(m)
    days = m.size
    return 0 if days < 7 

    if m[0] and m[days-1] and  m[0].trend and m[days - 1].trend
      diff = m[days - 1].trend - m[0].trend 
      last = diff / (days / 7)
    else
      last = nil 
    end
    if last
      return 0 - last
    else
      return 0
    end
  end

  def last(d)
    m = measure_range(Time.now - d.days, Time.now)
    return trend_range(m)
  end

  def measure_range(start_date, end_date)
    Measure.where('person_id = ? and measure_date >= ? and measure_date <= ?',
                  self.id, start_date.to_s(:db), end_date.to_s(:db)).order('measure_date desc')
  end

  def in3months
    three_month_trend current_measure
  end

  def three_month_trend(measure)
    ms = self.measure_range(measure.measure_date, measure.measure_date - 10.days)
    tr = trend_range(ms)
    measure.item + (tr * 4 * 3) if tr and measure
  end

  def current_measure
    measures = Measure.where(:person_id => self.id).order('measure_date desc').limit(1)
    return measures[0]
  end

  def karma_rank
    karma_rank = 1
    measures = Measure.where(:person_id => self.id)

    measures.each do |measure|
      if measure.karma 
        if current_measure.karma
          if measure.karma > current_measure.karma
            karma_rank = karma_rank + 1 
          end
        end
      end
    end
    return karma_rank
  end

  def leanbodymass
    weight - fat
  end

  def get_measures(num)
    Measure.where(:person_id => self.id).order('measure_date desc').limit(num)
  end

  def wuser
    wuser = Withings::User.info(self.withings_id, self.withings_api_key)
  end

  def refresh_all
    page = 1
    per_page = 40
    has_more = true
    measures_count = 0

    wuser = self.wuser
    wuser.share()

    last_weight = self.current_measure
    puts last_weight.to_yaml

    while has_more
      measurements = wuser.measurement_groups(:per_page => per_page, 
                                              :page => page, 
                                              :start_at => last_weight==nil ? Time.at(0) : last_weight.measure_date + 1,
                                              :end_at => Time.now) 
      has_more = measurements.size == per_page
      measures_count = measures_count + measurements.size

app/controllers/people_controller.rb
class PeopleController < ApplicationController
# before_filter :authenticate_person!
  skip_before_filter :authenticate_person!, :only => [:view]

  def index
    @people = Person.all
  end

  def rss
    @person = Person.find params[:id]
    @reports = @person.progress_report
    @measures = @person.get_measures(7)

    render :layout => false
    response.headers["Content-Type"] = "application/xml; charset=utf-8"
  end

  def new
    @person = Person.new
  end

  def overview
    @person = Person.find(params[:id])
    #@all_workout_days = @person.all_workout_days(@person.first_workout_date)
    @all_workout_days = @person.all_workout_days
    @workouts = Kaminari.paginate_array(@all_workout_days[:workouts]).page(params[:page]).per(10)
    @month_measures = @person.all_measure_days(Time.now.to_date - 30.days)
    @all_measures = @person.all_measure_days
  end

  def create
    @person = Person.new(params[:person])
    if @person.save
      #session[:person_id] = @person.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def show
    @person = Person.find(params[:id])
    @measures = @person.measures.order('measure_date desc').page(params[:page]).per(@person.measures_to_show || 7)

    if @person.nil?
      redirect_to root_url, :notice=>'?'
    else
      render
    end
  end

  def dashboard
    @person = Person.find(params[:id])
    render :layout => 'mobile'
  end

  def edit
    @person = current_person
  end

  def update
    @person = current_person
    if @person.update_attributes(params[:person])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= simple_form_for @person do |f| %>
  <%= f.input :username, :label => 'Your username please' %>
  <%= f.input :private %>
  <%= f.input :email %>
  <%= f.input :measures_to_show %>
  <%= f.input :height_feet %>
  <%= f.input :height_inches %>
  <%= f.input :alpha %>
  <%= f.input :binge_percentage %>
  <%= f.input :goal %>
  <%= f.input :workout_goal %>
  <%= f.input :withings_id %>
  <%= f.input :withings_api_key %>
  <%= f.button :submit %>
<% end %>

<%= form_for @person do |f| %>
  <p><%= f.submit (@person.new_record? ? "Sign up" : "Update") , :class=>'btn large primary' %></p>
  <%= f.error_messages %>
  <table>
    <tr align='top'>
      <td>
        <p>
          <%= f.label :username %><br />
          <%= f.text_field :username %>
        </p>
        <p>
          <%= f.label :private %><br />
          <%= f.check_box :private %>
        </p>
        <p>
          <%= f.label :email, "Email Address" %><br />
          <%= f.text_field :email %>
        </p>
        <!--
        <p>
          <%= f.label :password %><br />
          <%= f.password_field :password %>
        </p>
        <p>
          <%= f.label :password_confirmation, "Confirm Password" %><br />
          <%= f.password_field :password_confirmation %>
        </p>
        -->
        <p>
          <%= f.label :measures_to_show %><br />
          <%= f.text_field :measures_to_show %>
        </p>
      </td>
      <td>
        <p>
          <%= f.label :goal_type %><br />
          <%= f.radio_button :goal_type, "lbs" %> lbs<br/>
          <%= f.radio_button :goal_type, "%fat" %> %fat
        </p>
        <p>
          <%= f.label :goal %><br />
          <%= f.text_field :goal %>
        </p>
        <p>
          <%= f.label :height_feet %><br />
          <%= f.text_field :height_feet %>
        </p>
        <p>
          <%= f.label :height_inches %><br />
          <%= f.text_field :height_inches %>
        </p>
        <p>
          <strong>Trend Alpha (suggested .1 - .25)</strong><br />
          <%= f.text_field :alpha %><br/>
        </p>
        <p>
          <strong>
            Binge detection
          </strong>
          <br>
          <%= f.text_field :binge_percentage %>
          </br>
        </p>
        <p>
          Email a daily report
          <br>
          <%= f.check_box :send_email %>
          </br>
        </p>
      </td>
    </tr>
        <tr>
          <td colspan='2'>
            To get your withings data, hit the Share button in your dashboard, and pick the Share on the web option.</br>
            <%= image_tag 'withings_api_key_etc.PNG', :size=>'800x300' %>
            <p>
              <%= f.label :withings_id %> User ID<br />
              <%= f.text_field :withings_id %>
            </p>
            <p>
              <%= f.label :withings_api_key %><br />
              <%= f.text_field :withings_api_key %>
              <p><%= f.submit (@person.new_record? ? "Sign up" : "Update") , :class=>'btn large primary' %></p>
            </p>
          </td>
        </tr>
      </table>
    <% end %>

    Avatars from <a href="http://en.gravatar.com/">gravatar.com</a><br/>
    <%= link_to "Update from Withings",  :controller=>"measures", :action=>"refresh" %>
    <br/>
    <%= link_to "Delete All Measures (careful!)", :controller=>"measures", :action=>"deleteall" %>

app/views/people/_measures_table.html.erb
<table width='100%' class="table table-striped">
  <tr>
    <th>#</th>
    <th>Weight</th>
    <th>Trend</th>
    <th>Karma *</th>
    <th>Grade</th>
    <th>Trend %</th>
    <th>Fat %</th>
    <th>BMI</th>
    <th>Measure Date</th>
    <% if person_signed_in? and current_person == @person %>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    <% end %>
  </tr>
  <% counter = 1 %>
  <% @measures.each do |measure| %>
    <tr>
      <td><%= counter %><% counter = counter + 1 %></td>
      <td <%= "class='binge'" if measure and measure.is_binge? %>><%= Utility.floatformat % measure.weight %></td>
      <td><%= Utility.floatformat % measure.trend if measure.trend %></td>
      <td><%= Utility.floatformat % measure.karma if measure.karma %></td>
      <td><strong><%= @person.karma_grade(measure) if measure.karma %></strong></td>
      <td>
        <% if (Utility.floatformat % measure.trend_percentage).to_i >= 100 %>
          <div class='label label-success'>
          <% else %>
            <div class='label label-important'>
            <% end %>
            <%= Utility.floatformat % measure.trend_percentage if measure %>
          </div>
        </td>
        <td><%= Utility.floatformat % measure.fatpercentage if measure.fat %></td>
        <td><%= Utility.floatformat % @person.get_bmi(measure.trend) if measure.trend %></td>
        <td><%= measure.measure_date.strftime('%a') %> <%= measure.measure_date.to_s(:short) %> (<%= time_ago_in_words(measure.measure_date) %>)</td>
        <% if person_signed_in? and current_person == @person %>
          <td><%= link_to "Edit", edit_measure_path(measure) %></td>
          <td><%= link_to "Delete", measure, :confirm => 'Are you sure?', :method => :delete %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= paginate @measures %>
<p>
  <small>  
    <ul>
      <li>
        Karma: If you are at your goal weight and not gaining you will have a karma of 100.
      </li>
      <li>
        Karma rank: How does your current karma compare with your best ever karma.
      </li>
      <li>
        <div class='binge'>
          Days above the trend are red.
        </li>
      </ul>
    </small>

app/views/people/_new_measure.html.erb
<% if current_person %>
  <%= form_for Measure.new do |f| %>
    <%= f.error_messages %>

    <%= f.hidden_field :person_id, :value=>current_person.id %>
    <%= f.hidden_field :measure_date, :value=>Time.now %> 
    <%= f.text_field :weight %>
    <%= f.submit 'Add new measure', :class=>'btn' %>
  <% end %>
<% end %>

app/views/people/_posts.html.erb
<table>
  <tr>
    <td>
      <strong>
        Posts
      </strong>
      <% if @posts.size %>
        <ul>
          <% @posts.each do |post| %>
            <li>
              <small>
              <%= link_to post.name, post %>
            </small>
            </li>
          <% end %>
        <% end %>
      </td>
    </tr>
  </table>

app/views/people/_stats.html.erb
<% all_day_count = @person.days_since_first_workout %>
<% all_workouts = @person.workouts.where('rating > 0') %>
<% workouts_30 = @person.workouts_in_last_days(30) %>

<table class="table">
  <tr>
    <td>
      First recorded workout:
    </td>
    <td>
        <%= @person.days_since_first_workout %> days ago
    </td>
    <td>
        <%= all_workouts.first.workout_date.to_s(:long) %>
    </td>
  </tr>
  <tr>
    <td>
      Ever:
    </td>
    <td>
      <%= ((all_workouts.size.to_f / all_day_count.to_f) * 100).round(2).to_s %>%
    </td>
    <td>
      <%= all_workouts.size %>
      &nbsp;
    </td>
  </tr>
  <tr>
    <td>
      30 Days:
    </td>
    <td>
      <%= ((workouts_30.size.to_f / 30.to_f) * 100).round(2).to_s %>%
    </td>
    <td>
      <%= workouts_30.size %>
    </td>
  </tr>
</table>

app/views/people/_weight_chart.html.erb
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">

  // Load the Visualization API and the piechart package.
google.load('visualization', '1.0', {'packages':['corechart']});

// Set a callback to run when the Google Visualization API is loaded.
google.setOnLoadCallback(drawChart);


// Callback that creates and populates a data table, 
// instantiates the pie chart, passes in the data and
// draws it.
function drawChart() {

  // Create the data table.
  var data = new google.visualization.DataTable();
  data.addColumn('date', 'Date');
  data.addColumn('number', 'Weight');
  data.addColumn('number', 'Goal');
  data.addColumn('number', 'Trend');
  data.addRows([
      <% measures[:weight].each do |score| %>
        [new Date(<%= score[0].to_date.year.to_s + ',' + 
                  (score[0].to_date.month - 1).to_s + ',' +
                  score[0].to_date.day.to_s %>), 
        <%= score[1] %>,
        <%= @person.goal %>,
        <%= measures[:trend_days][score[0]] %>],
      <% end %>
      ]);

  // Set chart options
  var options = {'title':'Weight Month',
    'width':1000,
    'height':200};

  // Instantiate and draw our chart, passing in some options.
  var chart = new google.visualization.LineChart(document.getElementById('weight_chart_div'));
  chart.draw(data, options);
}
</script>
<div id="weight_chart_div" style="width:1000; height:200"></div>

app/views/people/_weight_chart_all.html.erb
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">

  // Load the Visualization API and the piechart package.
google.load('visualization', '1.0', {'packages':['corechart']});

// Set a callback to run when the Google Visualization API is loaded.
google.setOnLoadCallback(drawChart);


// Callback that creates and populates a data table, 
// instantiates the pie chart, passes in the data and
// draws it.
function drawChart() {

  // Create the data table.
  var data = new google.visualization.DataTable();
  data.addColumn('date', 'Date');
  data.addColumn('number', 'Weight');
  data.addColumn('number', 'Goal');
  data.addColumn('number', 'Trend');
  data.addRows([
      <% measures[:weight].each do |score| %>
        [new Date(<%= score[0].to_date.year.to_s + ',' + 
                  (score[0].to_date.month - 1).to_s + ',' +
                  score[0].to_date.day.to_s %>), 
        <%= score[1] %>,
        <%= @person.goal %>,
        <%= measures[:trend_days][score[0]] %>],
      <% end %>
      ]);

  // Set chart options
  var options = {'title':'Weight Ever',
    'width':1000,
    'height':200};

  // Instantiate and draw our chart, passing in some options.
  var chart = new google.visualization.LineChart(document.getElementById('weight_chart_all_div'));
  chart.draw(data, options);
}
</script>
<div id="weight_chart_all_div" style="width:1000; height:200"></div>

app/views/people/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/people/index.html.erb
<table width='800' class='table'>
  <% @people.each do |person|%>
    <tr>
      <td>
        <%= image_tag(person.gravatar_url) if Person.online %>
        <%= link_to person.name!, overview_person_path(person) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/people/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

app/views/people/overview.html.erb
<h1>
  <%= image_tag @person.gravatar_url if Person.online %> <%= @person.name! %> 
</h1>

<ul class="nav nav-pills">
  <li class="active">
  <%= link_to 'Overview', '#' %>
  </li>
  <li>
  <%= link_to 'Weight', @person %>
  </li>
  <% if current_person %>
    <li>
    <%= link_to 'New Workout', new_workout_path, :class => 'btn btn-small' %>
    </li>
  <% end %>
</ul>

<% if false %>
  <%= render :partial => 'weight_chart', :locals => { :measures => @month_measures } %>
  <br/>
  <%= render :partial => 'weight_chart_all', :locals => { :measures => @all_measures } %>
  <br/>
  <%= render 'workout_chart' %>
<% end %>


<%= Time.now.to_s(:long) %>

<%= render 'stats' %>

<table class='table table-compressed table-striped'>
  <thead>
    <tr>
      <th></th>
      <th colspan='3'><center>Weight Overview</center></th>
      <th colspan='4'><center>Workout Overview</center></th>
    </tr>
    <tr>
      <th>When</th>
      <th>Weight</th>
      <th>Goal</th>
      <th>Karma</th>
      <th>Grade</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Streak</th>
      <th>7 Day Score</th>
      <th>Grade</th>
      <th></th>
    </tr>
  </thead>

  <% @measures = @all_measures %>

  <% @workouts.each do |workout| %>
    <tr>
      <td>
        <% if workout.workout_date %>
          <%= workout.workout_date.to_s(:slim) %>
          (<%= time_ago_in_words workout.workout_date %> ago)
        <% else %>
          -
        <% end %>
      </td>
      <td>
        <% w = @measures[:weight][workout.workout_date.to_date] %>
        <%= Utility.floatformat % w.to_f if w %>
      </td>
      <td>
        <%= Utility.floatformat % (w - @person.goal).to_f if w %>
      </td>
      <td>
        <% k = @measures[:karma][workout.workout_date.to_date] %>
        <%= Utility.floatformat % k if k %>
      </td>
      <td><strong><%= Person.grade(k) if k %></strong></td>
      <td><%= workout.rating.nil? ? '-' : workout.rating %></td>
      <td><%= workout.description.nil? ? '-' : truncate(workout.description) %></td>
      <td><%= @all_workout_days[:streak][workout.workout_date.to_date] %></td>
      <td>
        <%= @all_workout_days[:against_goal][workout.workout_date.to_date].to_s %> /
        <%= @all_workout_days[:scores][workout.workout_date.to_date].to_s %>
      </td>
      <td><strong><%= Person.grade(@all_workout_days[:scores][workout.workout_date.to_date]) %></strong></td>
      <% if person_signed_in? and current_person.id == workout.person.id %>
        <td>
          <% if workout.id %>
            <%= link_to 'Edit', edit_workout_path(workout) %> |
            <%= link_to 'Delete', workout, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
<%= paginate @workouts %>
<br />

app/views/people/show.html.erb
<h1>
  <%= image_tag @person.gravatar_url if Person.online %> <%= @person.name! %> 
  <small>
    Goal:<strong> <%= @person.goal.to_s %></strong>. 
    Trend in 3 months:<strong><%= Utility.floatformat % @person.in3months if @person.in3months %></strong>
    Karma rank: <strong><%= @person.karma_rank if @person.karma_rank %></strong>.
    Karma grade: <strong><%= @person.karma_grade @person.current_measure %></strong>
  </small>
</h1>

<ul class="nav nav-pills">
  <li>
  <%= link_to 'Overview', overview_person_path(@person) %>
  </li>
  <li class="active">
  <%= link_to 'Weight', @person %>
  </li>
  <% if current_person %>
    <li>
    <%= link_to 'New Workout', new_workout_path, :class => 'btn btn-small' %>
    </li>
  <% end %>
</ul>


<% if person_signed_in? && current_person == @person %>
  <% if @measures.size == 0 %>
    <div class="alert-message"> 
      If you have no measures yet you might want to <%= link_to "Update from Withings",  :controller=>"measures", :action=>"refresh" %>
    </div>
  <% end %>
<% end %>
<% size = '300x150' %>

<% if Person.online %>
  <div class='row'>
    <div class='span4'>
      <%= 'You need at least 7 measures to derive trend data.' if @measures.size < 7 %>
      <% if @person.get_measures(7) and @person.last(7)%>
        <img src=<%= Measure.getchart(@person.get_measures(10), size) %>/>
      <% end %>
    </div>
    <div class='span4'>
      <% if @person.last(30) %>
        <img src=<%= Measure.getchart(@person.get_measures(30), size) %>/>
      <% end %>
    </div>
    <div class='span4'>
      <% if @person.measures.size and @person.last(@person.measures.size) %>
        <img src=<%= Measure.getchart(@person.get_measures(@person.measures.size), size) %>/>
      <% end %>
    </div>
  <% end %>

  <div class='row'> 
    <div class='span12'>
      <%= render 'measures_table' %>
    </div>
  </div>
</div>
<%= render 'new_measure' %>
<% @posts = @person.posts %>
<%= render 'posts' %>