config/routes.rb
Slim::Application.routes.draw do
  resources :workouts do
    member do
      get 'clone'
    end
  end

  devise_for :people
  resources :people do
    resources :workouts
    member do
      get 'dashboard'
      get 'overview'
    end
  end
  resources :bps

  devise_scope :person do
    get "/logout" => "devise/sessions#destroy"
  end

  resources :posts

  match 'measures/deleteall' => 'measures#deleteall'
  match 'measures/refresh' => 'measures#refresh'
  match 'measures/import' => 'measures#import'
  match 'measures/update_trend' => 'measures#update_trend'

  resources :measures
  match 'person/edit' => 'people#edit', :as => :edit_current_person

  match 'chart' => 'measures#chart'

  root :to => "people#index"

end

app/models/bp.rb
class Bp < ActiveRecord::Base
  belongs_to    :person
end

app/controllers/bps_controller.rb
class BpsController < ApplicationController
  # GET /bps
  # GET /bps.json
  def index
    @bps = Bp.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bps }
    end
  end

  # GET /bps/1
  # GET /bps/1.json
  def show
    @bp = Bp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bp }
    end
  end

  # GET /bps/new
  # GET /bps/new.json
  def new
    @bp = Bp.new
    @bp.person_id = current_person.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bp }
    end
  end

  # GET /bps/1/edit
  def edit
    @bp = Bp.find(params[:id])
  end

  # POST /bps
  # POST /bps.json
  def create
    @bp = Bp.new(params[:bp])

    respond_to do |format|
      if @bp.save
        format.html { redirect_to @bp, notice: 'Bp was successfully created.' }
        format.json { render json: @bp, status: :created, location: @bp }
      else
        format.html { render action: "new" }
        format.json { render json: @bp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bps/1
  # PUT /bps/1.json
  def update
    @bp = Bp.find(params[:id])

    respond_to do |format|
      if @bp.update_attributes(params[:bp])
        format.html { redirect_to @bp, notice: 'Bp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bps/1
  # DELETE /bps/1.json
  def destroy
    @bp = Bp.find(params[:id])
    @bp.destroy

    respond_to do |format|
      format.html { redirect_to bps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bps_helper.rb
module BpsHelper
end

app/views/bps/_form.html.erb
<%= simple_form_for @bp do |f| %>
  <%= f.association :person, :as => :hidden %>
  <%= f.input :dia, :label => 'Diastolic' %>
  <%= f.input :sys, :label => 'Systolic' %>
  <%= f.button :submit, :class => 'btn-primary' %>
<% end %>

app/views/bps/edit.html.erb
<h1>Editing bp</h1>

<%= render 'form' %>

<%= link_to 'Show', @bp %> |
<%= link_to 'Back', bps_path %>

app/views/bps/index.html.erb
<h1>Listing bps</h1>

<table class='table'>
  <tr>
    <th>Person</th>
    <th>Dia</th>
    <th>Sys</th>
    <th>Measure date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bps.each do |bp| %>
  <tr>
    <td><%= bp.dia %></td>
    <td><%= bp.person_id %></td>
    <td><%= bp.sys %></td>
    <td><%= bp.measure_date %></td>
    <td><%= link_to 'Show', bp %></td>
    <td><%= link_to 'Edit', edit_bp_path(bp) %></td>
    <td><%= link_to 'Destroy', bp, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bp', new_bp_path %>

app/views/bps/new.html.erb
<h1>New bp</h1>

<%= render 'form' %>

<%= link_to 'Back', bps_path %>

app/views/bps/show.html.erb
<p>
  <b>Person:</b>
  <%= @bp.person.name! %>
</p>

<p>
  <b>Dia:</b>
  <%= @bp.dia %>
</p>

<p>
  <b>Sys:</b>
  <%= @bp.sys %>
</p>

<p>
  <b>Measure date:</b>
  <%= @bp.created_at.to_s(:long) %>
</p>


<%= link_to 'Edit', edit_bp_path(@bp) %> |
<%= link_to 'Back', bps_path %>