config/routes.rb
Slim::Application.routes.draw do
  resources :workouts do
    member do
      get 'clone'
    end
  end

  devise_for :people
  resources :people do
    resources :workouts
    member do
      get 'dashboard'
      get 'overview'
    end
  end
  resources :bps

  devise_scope :person do
    get "/logout" => "devise/sessions#destroy"
  end

  resources :posts

  match 'measures/deleteall' => 'measures#deleteall'
  match 'measures/refresh' => 'measures#refresh'
  match 'measures/import' => 'measures#import'
  match 'measures/update_trend' => 'measures#update_trend'

  resources :measures
  match 'person/edit' => 'people#edit', :as => :edit_current_person

  match 'chart' => 'measures#chart'

  root :to => "people#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :name, :body, :person_id, :start_date, :end_date

  belongs_to :person
  validates_presence_of :person, :name, :body, :start_date, :end_date

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.order('created_at desc')
  end

  def show
    @post = Post.find(params[:id])
    @measures = Measure.where('measure_date > ? and measure_date < ?', @post.start_date, @post.end_date) 
  end

  def new
    unless person_signed_in?
      redirect_to :posts, :notice => "You must be logged in."
    end
    @post = Post.new
    @post.start_date = Time.now.to_date - 14.days
    @post.end_date = Time.now.to_date
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      redirect_to @post, :notice => "Successfully created post."
    else
      render :action => 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
    unless person_signed_in?
      redirect_to @post, :notice => "You must be logged in."
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to @post, :notice  => "Successfully updated post."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    unless person_signed_in?
      redirect_to :posts, :notice => "You must be logged in."
    end
    @post.destroy
    redirect_to posts_url, :notice => "Successfully destroyed post."
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% @post.person_id = current_person.id %>
<%= simple_form_for @post do |f| %>
  <%= f.input :name, :input_html => { :size => 100 } %>
  <%= f.input :body, :input_html => { :size => '100x10' } %>
  <%= f.input :start_date, :order => [:month, :day, :year] %>
  <%= f.input :end_date, :order => [:month, :day, :year] %>
  <%= f.input :person_id, :as => :hidden %>
  <%= f.button :submit %>
<% end %>

app/views/posts/edit.html.erb
<% title "Edit Post" %>

<%= render 'form' %>

<p>
  <%= link_to "Markdown Syntax", "http://daringfireball.net/projects/markdown/syntax" %> | 
  <%= link_to "Show", @post %> |
  <%= link_to "View All", posts_path %>
</p>

app/views/posts/index.html.erb
<% title "Posts" %>

<table class='table'>
  <tr>
    <th>Name</th>
    <th>Person</th>
    <th>Date</th>
  </tr>
  <% for post in @posts %>
    <tr>
      <td><%= link_to post.name, post %></td>
      <td><%= post.person.username %></td>
      <td><%= post.created_at.to_s(:long) %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Post", new_post_path %></p>

app/views/posts/new.html.erb
<% title "New Post" %>

<%= render 'form' %>

<%= link_to "Markdown Syntax", "http://daringfireball.net/projects/markdown/syntax" %> | 
<p><%= link_to "Back to List", posts_path %></p>

app/views/posts/show.html.erb
<h1>
  <%= @post.name %>
  <small>
    <br>
    <%= @post.person.username %> - <%= @post.created_at.to_s(:long) %>
    </br>
  </small>
</h2>

<% size = '600x250' %>

<center>
  <img src=<%= Measure.getchart(@measures, @measures.size.to_s + " Day Trend " + 
                         Utility.floatstringlbs(@post.person.trend_range(@measures).to_s), 
                         @measures.size, 
                         @post.person, size) %>>
                         <br>
                         <%= @post.start_date.to_s(:long) %> - <%= @post.end_date.to_s(:long) %>
                         </br>
                       </center>

                       <%= raw RDiscount.new(@post.body).to_html %>

                      <p>
                        <%= link_to "Edit", edit_post_path(@post) %> |
                        <%= link_to "Delete", @post, :confirm => 'Are you sure?', :method => :delete %> |
                        <%= link_to "View All", posts_path %>
                      </p>